name: stats
dependencies:
# - python=3.8.13
- pandas
- numpy=1.19.2
- six=1.15.0
- absl-py=0.10
- flatbuffers=1.12.0
- gast=0.3.3
- grpcio~=1.32
- libclang>=9.0.1
- protobuf<3.20,>=3.9.2
- tensorflow-estimator<2.5.0,>=2.4.0
- typing-extensions~=3.7.4
- wrapt=1.12.1
- tensorflow
- keras
- numpy
- scikit-learn